name: Test MacOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: node
    - name: Check
      run: |
        node -v
        npm -v
